[project]
name = "redis-celery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "celery>=5.6.0",
    "fastapi[standard]>=0.128.0",
    "python-dotenv>=1.2.1",
    "redis>=7.1.0",
    "uvicorn[standard]>=0.40.0",
]
